# Generated by Django 4.2 on 2023-05-05 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-role", "username"],
                "verbose_name": "Пользователи",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="personal_info",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personal_info",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Мужской"), ("female", "Женский")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="personal_info",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
        migrations.AddField(
            model_name="personal_info",
            name="rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="personal_info",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_info",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
