# Generated by Django 4.2 on 2023-05-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_location_latitude_location_longitude"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name": "Новости", "verbose_name_plural": "Новости"},
        ),
        migrations.RemoveField(
            model_name="news",
            name="user",
        ),
        migrations.AlterField(
            model_name="news",
            name="content",
            field=models.TextField(verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Роль (Сотрудник-0, Hr-1)"
            ),
        ),
    ]
