# Generated by Django 4.2 on 2023-05-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_news_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image",
            field=models.ImageField(
                default="default_image.jpg",
                upload_to="news_images",
                verbose_name="Изображение",
            ),
        ),
    ]
