# Generated by Django 4.2 on 2023-05-20 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_news_image"),
    ]

    operations = []
