# Generated by Django 4.2 on 2023-05-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_auto_20230520_2152"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="datetime",
            field=models.DateTimeField(null=True),
        ),
    ]
