# Generated by Django 4.2 on 2023-05-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_interview_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.CharField(
                choices=[
                    ("1", "1 звезда"),
                    ("2", "2 звезды"),
                    ("3", "3 звезды"),
                    ("4", "4 звезды"),
                    ("5", "5 звезд"),
                ],
                max_length=1,
            ),
        ),
    ]
